### ISSUE TITLE
The photoshop script is not working with Adobe Photoshop CC 2015.5

### ISSUE THREAD

**Issue by Xakaloz** [craigathook/alpha-jpeg#1]
Hi.
First of all, thank you for this nice library.

Your script is not working in in Adobe Photoshop CC 2015.5.

The 4th command "Define selection" is not available , and all the "Select layer "Layer X" after that too. 

Thank you.

**Comment by Xakaloz** [comment]
Got it.

It's just because I have my photoshop in french and it does not find the layers by their names in your script (Layers are called "Calque").

Maybe you can put a note about that in your readme for foreigners :)

Thank you.

**Comment by craigathook** [comment]
hey! thanks for pointing this out. i changed the photoshop action so that it gives names to the layers. this should avoid issues with default names of layers being different in other languages. if you have time, please download the latest action and let me know if it works for you!

**Comment by Xakaloz** [comment]
Hey! You're new action script is working like a charm ;)
